name: 'Setup Node.js & pnpm'
description: 'Sets up Node.js, pnpm, and installs dependencies with advanced caching'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup Vite cache
      uses: actions/cache@v4
      with:
        path: node_modules/.vite
        key: ${{ runner.os }}-vite-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-vite-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
